<?php
// includes/blog-data.php — single source of truth for all blog post metadata.
// Newest post FIRST. Every consumer (blog index, homepage preview, related
// articles, sitemap.php) reads this array. Never hardcode post lists elsewhere.

$blogPosts = [
    [
        'slug'     => 'off-grid-heating-options-eastern-oregon',
        'title'    => 'Best Heating Options for Off-Grid Homes in Eastern Oregon',
        'excerpt'  => 'Heating an off-grid home in Eastern Oregon is not just about picking a stove or furnace. The best plan depends on your home size, insulation, solar system, fuel access, and winter road conditions. Here\'s how to think through wood stoves, heat pumps, propane, radiant floor heat, passive solar, and backup systems before construction starts.',
        'image'    => '/assets/images/blog/off-grid-home-framing.webp',
        'alt'      => 'Custom home framing in progress on rural land in Eastern Oregon near Grant County — coordinating insulation, mechanical room placement, and structural layout for an off-grid home heating system',
        'date'     => 'June 6, 2026',
        'dateISO'  => '2026-06-06',
        'category' => 'Construction & Building Tips',
        'readtime' => '24 min read',
    ],
    [
        'slug'     => 'off-grid-solar-power-eastern-oregon',
        'title'    => 'Solar Power for Off-Grid Homes in Eastern Oregon',
        'excerpt'  => 'Off-grid solar is more than panels on a roof. A reliable system includes battery storage, backup generation, proper mechanical space, and a home designed to minimize waste. Here\'s what every off-grid homeowner in Eastern Oregon needs to plan before construction starts — especially for winter.',
        'image'    => '/assets/images/blog/eastern-oregon-high-desert-site.webp',
        'alt'      => 'Eastern Oregon high desert terrain near Grant County — planning an off-grid home site with solar exposure, battery storage, generator placement, and mechanical room layout',
        'date'     => 'June 6, 2026',
        'dateISO'  => '2026-06-06',
        'category' => 'Construction & Building Tips',
        'readtime' => '22 min read',
    ],
    [
        'slug'     => 'off-grid-septic-systems-eastern-oregon',
        'title'    => 'Septic Systems for Off-Grid Homes in Eastern Oregon',
        'excerpt'  => 'The septic system can be one of the biggest factors in whether a rural Eastern Oregon property is practical to build on. The drain field location, soil conditions, required setbacks, and available area affect where the home can sit, where the driveway goes, and where the well needs to be placed. Here\'s what to know before you build.',
        'image'    => '/assets/images/blog/raw-land-eastern-oregon.webp',
        'alt'      => 'Raw land in Eastern Oregon high desert near Grant County — evaluating a rural parcel for off-grid home construction including septic site evaluation, drain field placement, and well setbacks',
        'date'     => 'June 6, 2026',
        'dateISO'  => '2026-06-06',
        'category' => 'Construction & Building Tips',
        'readtime' => '20 min read',
    ],
    [
        'slug'     => 'off-grid-water-systems-eastern-oregon',
        'title'    => 'How Do You Get Water for an Off-Grid Home in Eastern Oregon?',
        'excerpt'  => 'Water planning should happen before the floor plan is finalized. A rural property may have the views and privacy you want — but if the well, cistern, pump system, freeze protection, and septic layout are not coordinated early, the project becomes expensive fast. Here\'s what every off-grid water system in Eastern Oregon needs.',
        'image'    => '/assets/images/blog/eastern-oregon-high-desert-site.webp',
        'alt'      => 'Eastern Oregon high desert terrain near Grant County — site planning for an off-grid home water system including well location, cistern placement, and freeze protection',
        'date'     => 'June 6, 2026',
        'dateISO'  => '2026-06-06',
        'category' => 'Construction & Building Tips',
        'readtime' => '18 min read',
    ],
    [
        'slug'     => 'off-grid-home-permits-oregon',
        'title'    => 'Do You Need Permits to Build an Off-Grid Home in Oregon?',
        'excerpt'  => 'Off-grid means your home generates its own power and manages its own water and waste — it does not mean you can skip building permits. Here\'s what permit categories apply to off-grid construction in Oregon, from structural and electrical to septic and land use.',
        'image'    => '/assets/images/custom-home-framing.webp',
        'alt'      => 'Custom home framing in progress on rural land in Eastern Oregon — off-grid home construction requires building permits, electrical permits, mechanical permits, and septic approval in Oregon',
        'date'     => 'June 6, 2026',
        'dateISO'  => '2026-06-06',
        'category' => 'Construction & Building Tips',
        'readtime' => '16 min read',
    ],
    [
        'slug'     => 'off-grid-home-cost-eastern-oregon',
        'title'    => 'What It Costs to Build an Off-Grid Home in Eastern Oregon',
        'excerpt'  => 'Building off-grid is not just the cost of the house. The total budget depends on the home itself, the land, access road, site prep, well, septic, solar, and how remote the property is. Here\'s what every budget category includes and why site conditions are the biggest variable.',
        'image'    => '/assets/images/blog/off-grid-home-framing.webp',
        'alt'      => 'Custom home construction framing in Eastern Oregon — building an off-grid home on rural land near Mount Vernon and Grant County',
        'date'     => 'June 6, 2026',
        'dateISO'  => '2026-06-06',
        'category' => 'Construction & Building Tips',
        'readtime' => '14 min read',
    ],
    [
        'slug'     => 'building-off-grid-home-raw-land-eastern-oregon',
        'title'    => 'Can You Build Off-Grid on Raw Land in Eastern Oregon?',
        'excerpt'  => 'Buying rural land around Mount Vernon, John Day, or Prairie City and actually building on it are two different things. Here\'s what to check before you commit — access, permits, wells, septic, solar, site prep, and why calling a builder first saves money.',
        'image'    => '/assets/images/blog/raw-land-eastern-oregon.webp',
        'alt'      => 'Raw land in Eastern Oregon high desert — evaluating a parcel for off-grid home construction near Grant County',
        'date'     => 'June 6, 2026',
        'dateISO'  => '2026-06-06',
        'category' => 'Construction & Building Tips',
        'readtime' => '11 min read',
    ],
    [
        'slug'     => 'off-the-grid-living-oregon',
        'title'    => 'Off-the-Grid Living in Oregon: Embracing Self-Reliance',
        'excerpt'  => 'Oregon\'s stunning landscapes make it a dream destination for off-grid living. But success demands careful planning — especially given the state\'s variable climate, regulations, and the critical importance of a knowledgeable local contractor.',
        'image'    => '/assets/images/blog/off-grid-homestead-oregon.webp',
        'alt'      => 'Off-grid homestead in rural Oregon with Pacific Northwest forest backdrop',
        'date'     => 'June 6, 2026',
        'dateISO'  => '2026-06-06',
        'category' => 'Construction & Building Tips',
        'readtime' => '8 min read',
    ],
];
